default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - "--indent=2"
          - "--autofix"
      - id: check-json
      - id: check-yaml
        exclude: ^Deploy/
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.13
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [ --fix, --unsafe-fixes ]

  - repo: https://github.com/pycqa/flake8
    rev: '7.3.0'
    hooks:
      - id: flake8
        args: ["--config=pyproject.toml"]
        additional_dependencies: ["flake8-pyproject", "wemake-python-styleguide"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.17.1'
    hooks:
      - id: mypy
        args: [ "--install-types", "--non-interactive" ]
