force-exclude = true
line-length = 120
indent-width = 4
output-format = "grouped"
target-version = "py313"

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
docstring-code-format = true

[lint]
fixable = ["ALL"]
select = ["ALL"]
ignore = [
    'ANN002', 'ANN003',
    'COM812',
    'D100', 'D101', 'D103', 'D102', 'D104', 'D105', 'D106', "D107", "D400",
    'D203', 'D205',
    "G004",
    "FIX002",
    'ISC001',
    "TD002", "TD003",
    "PT",
    "TD001", "TID252"]

external = []


[lint.flake8-annotations]
mypy-init-return = true
ignore-fully-untyped = true
allow-star-arg-any = true

[lint.pydocstyle]
convention = "pep257"

[lint.isort]
force-single-line = false
force-wrap-aliases = true
force-sort-within-sections = true
combine-as-imports = true
lines-after-imports = 2

[lint.mccabe]
max-complexity = 5
